[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_russian_roulette = "7kw5LM3xMyr51Zpsgznh64pNcucoodFkcnJztRfHBLJj"

[programs.localnet]
solana_russian_roulette = "7kw5LM3xMyr51Zpsgznh64pNcucoodFkcnJztRfHBLJj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
