[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_russian_roulette = "CwSeMKEj7gZ9E1p7tkszuJkwzN2u8gHbD4wMXQuVQrNV"

[programs.localnet]
solana_russian_roulette = "CwSeMKEj7gZ9E1p7tkszuJkwzN2u8gHbD4wMXQuVQrNV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
